steamclock/bluejay

.gitignore, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Connection.swift, Bluejay/Bluejay/ConnectionObserver.swift, Bluejay/Bluejay/Queue.swift, README.md
Previously Bluejay doesn't quite understand why `didDisconnectPeripheral` is called, and therefore whenever it is called, sometimes it would trigger auto reconnect, sometimes it won't. This behaviour can be unpredictable in some cases, and cause unexpected re-connection attempts.
The issues centre around how `didDisconnectPeripheral` is multi-purpose and called by Core Bluetooth when you:
1. Cancel a pending connection
2. Cancel a connection to a connected peripheral (i.e. disconnect from it explicitly)
3. Loses connection to a connected peripheral unexpectedly (e.g. going out of range)
Only the 3rd case should trigger auto reconnect, but Bluejay also needs to figure out why `didDisconnectPeripheral` is called.
To figure out the first case: use the `isConnecting` state, and have the …
=> Improve handling of disconnection and auto reconnect

Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Error.swift
It is best to only work with the synchronized peripheral while inside a background task. It is usually a programmer error to try to access something from the Bluejay interface while inside a background task, or an attempt to try to use the background task for something it is not designed for.
This PR adds some protection against doing things like calling `bluejay.write/read/listen`, or even `bluejay.scan` and `bluejay.disconnect` inside a background task. Doing so will either result in the incorrect calls failing immediately with the appropriate error, or not doing anything at all. In the latter case, a warning is printed to the console.
Additionally, I've added protection against calling `run:backgroundTask:...` simultaneously, or in close succession before the first one finishes. Only …
=> Prevent calling API on Bluejay while a background task is running

Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Peripheral.swift, Bluejay/BluejayDemo/HeartSensorViewController.swift, Bluejay/BluejayDemo/Main.storyboard, Bluejay/BluejayDemo/ScanHeartRateSensorsViewController.swift
This PR fixes the caching of listens for listen restoration, and adds a bit of support for managing those cached listens. It's only "a bit" because there are some tricky questions I don't have answers for yet, so I didn't want to add too much without getting a second opinion first.
Previously, cached listens were stored in a Dictionary with the Bluejay instance UUID as their keys. This is wrong because a Bluejay instance can be re-instantiated with a new and different UUID either by the user or by iOS during state restoration.
The fix uses the restore identifier as the keys in the Dictionary. The restore identifier is something that should remain constant and persist over not only different Bluejay instances, but the context of where and how Bluejay is used in the app as well.
There is …
=> Fix caching of listens and add a bit of support for managing cached listens

Bluejay/Bluejay/Bluejay.swift
Replaced `debugPrint()` with `log()` calls, to prepare for improving logging (see #106).
=> Replaced debugPrint() with log() calls

Bluejay/Bluejay/Bluejay.swift
Temporary fix for #98 until a more proper solution as proposed in #102 is implemented.
@larryonoff can you have a look and let me know if this will help? Thanks!
=> Fix mistaking a background restoration when Bluejay is initialized really early

Bluejay/Bluejay/PeripheralIdentifier.swift, Bluejay/Bluejay/Scan.swift, Bluejay/Bluejay/ScanDiscovery.swift
The following are included in PR
1. ScanDiscovery shouldn't expose CBPeripheral, should expose a PeripheralIdentifier #113
2. PeripheralIdentifier (maybe others) should conform to Equatable and Hashable #114 
PS. This may be two separate PRs. But it's really easier and cleaner to implement #113 with #114 ready.
=> Update scan discovery and extend peripheral identifier

Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/CBPeripheral+FindService.swift, Bluejay/Bluejay/CBService+FindCharacteristic.swift, Bluejay/Bluejay/Peripheral.swift, Bluejay/Bluejay/Queue.swift, Bluejay/Bluejay/Scan.swift, Bluejay/Bluejay/SynchronizedPeripheral.swift, Bluejay/BluejayDemo/HeartSensorViewController.swift, Bluejay/BluejayDemo/ScanEverythingViewController.swift, Bluejay/BluejayDemo/ScanHeartRateSensorsViewController.swift
* use `first(where:_)` instead of `filter` and then `first`
* remove redundant declarations from `Scan.swift`
* replace `fileprivate` with `private` since it's redundant in Swift 4
* use `Data` instead of `NSData`
* use `.` initialisation syntax when it's possible
=> Code cleanup

Bluejay.podspec, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Info.plist
- Transfer disconnect clean up responsibility to the background task if there is one
- Also fixes incorrect assumptions on what the states should be initially for auto reconnect, and when calling cancel everything - cancel everything is not the same as calling disconnect explicitly.
- Bump version to 0.4.2
=> Fix disconnect cleanup for bg task

Bluejay.podspec, Bluejay/Bluejay/Error.swift, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/SynchronizedPeripheral.swift
If a disconnect occurs during an end listen call in a write and listen operation, we need the end listen call to propagate that disconnection error back to the background task to allow it to catch and throw the disconnect error back to the background task's completion block.
=> Fix end listen for write and listen

Bluejay.podspec, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/SynchronizedPeripheral.swift
Apply the same recent fixes made to `writeAndListen` for `writeAndAssemble` as well:
- Better management of semaphore locks and releases
- Better usage of end listen
- Allow failing the operation if bluetooth becomes unavailable or if there's a disconnection after both the read and listen have been setup correctly
=> Fix write and assemble

Bluejay.podspec, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/SynchronizedPeripheral.swift
Helps prevent the run background task from getting stuck if a listen never gets any updates.
=> [v0.4.8] Add timeout to synchronized listen

Bluejay.podspec, Bluejay/Bluejay/Error.swift, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/SynchronizedPeripheral.swift
- Prevent indefinite flush
- Add missing cancellation handling
- Dedup listen semaphore signals
- Add missing semaphore signal for end listen
- Use timeout enum
=> [v0.4.9] Fix flush listen

Bluejay.podspec, Bluejay/Bluejay/Connection.swift, Bluejay/Bluejay/Info.plist
For #145
Rob has helped us discovered a bug where the second connection request can mistakingly cancel the first and still ongoing connection request, resulting in the second connection request not getting a callback.
=> [v0.5.0] Fix incorrect connection cancellation

Bluejay.podspec, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Info.plist
Thank you to @shekhar-suman who discovered this issue.
Previously the listeners were cached using the Bluejay instance uuid, but we've since switched to using the restore identifier, and the accessing of the listen cache wasn't updated.
=> [v0.5.1] Fix accessing of the listen cache

Bluejay.podspec, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Error.swift, Bluejay/Bluejay/Info.plist
See #119 for more information.
@larryonoff and @DrAma999 It would be great to get your feedback and review as well. Thanks!
=> [v0.6.0] Add stop and extract

Bluejay/Bluejay/Bluejay.swift
The `isListening` method is only available on a `Peripheral` instance, thus to understand if we are already listening to a specific characteristic the current process should be.
1. Create a `ConnectionObserver` object
2. In the `connected(to peripheral: Peripheral)` store the instance of the connected peripheral to a variable
3. When is needed ask the peripheral if someone is listening to a specific characteristic by using the `isListening` exposed from the `Peripheral` instance
This is due to the fact that from the `Bluejay` instance side the connected peripheral is not exposed.
I've added a method to the `Bluejay` class that basically asks the connected peripheral if it is listening for a specific characteristic, if no peripheral is connected it throws and error.
I'm wondering if you …
=> Is listening to characteristic method on connected peripheral

Bluejay.podspec, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/Scan.swift, CHANGELOG.md
Added a console warning and warning to `Bluejay.scan` to discourage accidentally scanning with `serviceProviders` set to `nil` or empty. 
I accidentally ran into this on another project and there was some discussion of adding a warning like this to prevent it happening again.
=> Add warnings to scan against leaving serviceIdentifiers set to `nil` or empty

Bluejay.podspec, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/Scan.swift, CHANGELOG.md
Fixes #171
This adds an optional parameter, `throttleRSSIDelta` to `scan` that defaults to the current value of 5, but allows users to increase or decrease the value to change how often repeat discoveries are reported. Setting the value to 0 will disable the check completely, since we're comparing the absolute value of the change in RSSI.
I'm not wild about the name of the parameter, `throttleRSSIDelta`, if someone's got a better suggestion I would gladly change it.
=> Add option to change threshold for throttling discoveries by RSSI

Bluejay/Bluejay/Bluejay.swift
- Crash when using `isBluetoothAvailable` prior to calling `start` on a Bluejay instance
- Need to be able to check that boolean before starting a Bluejay instance, #116
- Return false if Bluejay's central manager is nil and not yet initialized
- Tested using the demo app and debugPrint the boolean before calling start
- No longer crashes and returns false
=> Allow checking is bluetooth available before starting Bluejay

Bluejay.podspec, Bluejay/.jazzy.yaml, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Info.plist, Bluejay/BluejayHeartSensorDemo/SensorViewController.swift, Bluejay/DittojayHeartSensorDemo/DittojayViewController.swift
Fixes: #198 
@kylebrowning could you also review this PR? Thanks 👍🏻
This fix allows Bluejay to complete the disconnection clean up without crashing when a device is unpaired.
I've never triggered iOS' system pairing dialog before with Bluejay, because I've never worked with a characteristic that is encrypted, since most of our client projects deal with authentication upfront, not on per-characteristic basis.
But I agree this can be common, so this fix is important.
Anyhow, I didn't know we can also get a disconnection event while the connection operation is in the `running` state, which is exactly what happens when:
1. Bluejay is attempting to reconnect
2. If you unpair the device during a reconnect attempt
This fix simply adds that specific case, and provide the missing `connectingError` …
=> v0.8.3 - Fix unpairing crash

Bluejay.podspec, Bluejay/.jazzy.yaml, Bluejay/Bluejay/Info.plist, Bluejay/Bluejay/Queue.swift
Fixes: #196 
Thanks for the great bug report @jeffbk and @kylebrowning
Failing a queueable requires updating its queue, and therefore requires the queueable to have a reference to its queue. The disconnection-is-queued failure block is relatively new, so I didn't catch the new requirement - that is to shuffle the queue assignment to the new starting point of the add call.
This should fix specifically the crashes when you make Bluejay calls right after and during a queued disconnect, such as making a scan call right after the disconnect call.
However, I am not sure I fully understand this question:
> However, there is an additional issue that the startScan will fail because a disconnect is queued. It seems like this logic is misplaced as the Queue does not know wether the Queueable should …
=> Fix disconnect then scan crash

Bluejay.podspec, Bluejay/Bluejay.xcodeproj/project.pbxproj, Bluejay/Bluejay/Info.plist, Bluejay/DittojayHeartSensorDemo/Info.plist, README.md
We need to try running our library and demos using the latest Xcode, and make sure the basic Bluetooth operations still work on iOS 13.
Tested everything on iOS 13, and found and fixed a crash related to Bluetooth privacy statement. Also verified all basic Bluetooth operations such as scanning, reading, and writing still work as expected.
=> [223] Make sure the library, bluejay demo, and dittojay demo build and run on Xcode 11 and later

Bluejay.podspec, Bluejay/.jazzy.yaml, Bluejay/Bluejay.xcodeproj/project.pbxproj, Bluejay/Bluejay/BackgroundRestoreConfig.swift, Bluejay/Bluejay/BackgroundRestorer.swift, Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/ListenRestorer.swift, Bluejay/Bluejay/Scan.swift, CHANGELOG.md, Package.swift
This PR adds support for [Swift Package Manager](https://swift.org/package-manager/) which is now built into Xcode. It required adding `import UIKit` anywhere that those functions were called but otherwise caused no other changes.
=> Add Swift Package Manager support

Bluejay/Bluejay/Error.swift, Bluejay/Bluejay/SynchronizedPeripheral.swift
There were a couple of rare error states that could happen if timeouts happened in the middle of a multi part listen, or if writeAndAssemble received more data than expected that were not being handled correctly (could fail to throw an error, could leave the bluetooth stack in a weird state where late operations would fail).
- Throw a new `.tooMuchData` error for writeAndAssemble if the data overflows the expected length
- If the wait inside a synchronous background listen (listen, writeAndListen, writeAndAssemble) times out, always treat it as an error, even if there has also been some successful receipt of data.
Verified the behaviour of all the failure modes for write and assemble inside another app. The error edge cases for this are strange enough that it is a little tricky to test …
=> Fix problems with timeouts on listens not working as expected with partial data received or data overflow

Bluejay/Bluejay/Bluejay.swift, Bluejay/Bluejay/Peripheral.swift
As detailed in #239, when you are in a background task, there are currently cases where you can end up unable to exit the task when you are in a blocking listen either due to a disconnection or (also) intentionally via calling cancelEverything, because none of the errors generated by that will propagate to the listeners, which we can be blocked on. This behaviour also causes problems with implementing your own timeouts to work around #240 (which is hard to fix within Bluejay due to the behaviour of the semaphore timeouts), because there is no way to implement a timeout at the application level if calling cancelEverything will not actually cancel _everything_.
Add an option to allow errors sent in to cancelEverything to be propagated to all current listeners, this will allow background …
=> Add setting to broadcast errors sent to cancelEverything to all listeners
